name = "jack-and-jenna"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "jack-and-jenna-rsvp"
database_id = "6ecc4e63-3449-4e29-91fc-0612c25965c9"
